### ISSUE TITLE
用户体验感觉很糟糕

### ISSUE THREAD

**Issue by Hitomis** [mzule/FantasySlide#1]
效果做的非常好，我是来拜读的，然后觉得有以下三个问题：

1、两侧侧滑用手滑动出来的概率就50%吧，很不顺
2、通过侧滑拉出来的菜单，松手会自动关闭，这与用户一般使用习惯很不符合，最糟糕的是，松手后，由于你没有处理触摸事件，导致手指水平方向的菜单项会触发点击效果，然后莫名的进入了其他页面，PS：简言之：“我只是想滑动打开菜单，为什么怎么进入了其他页面？”
3、右侧也是滑动拉出后，手指必须一直按着，但是大多数人都是右手操作，如果右手大拇指一直按着屏幕，那么右侧菜单项偏下的位置就回被手挡着。

以上是我的使用体验。
也可能是我的操作习惯适应不了这个设计。 
@mzule

**Comment by mzule** [comment]
这个库和其他的侧边栏不同，这是划出来手指不离开屏幕直接选择，松手就可以完整选择菜单。是我在 readme 里面没有说明白，我会补充说明一下的。

下面针对你的问题一一解答。

1、如果不松手菜单都是能划出来的。
2、这个库没有打开菜单这个手势，但是可以通过按钮调用打开。
3、手指被遮挡的问题的确会出现，所以这个库要看应用场景了，可以通过 listener 在其他地方给予提示。

最后，感谢你的建议，这个库的实用价值的确有限。我创建这个库的原因，主要就是看到 dribbble 上的那个效果图很炫，也是很有创意的交互方式，有实现的欲望。

感谢。

https://dribbble.com/shots/2269140-Force-Touch-Slide-Menu
