### ISSUE TITLE
代码问题咨询

### ISSUE THREAD

**Issue by erhutime** [mzule/FantasySlide#2]
在SideBar类中，有一个全局变量opened,    在SetTouch方法中，  有如下代码opened = percent == 1;
其中percent是这个方法的参数，剩下的代码就没有更改过这个变量的状态值了，只是用来进行一些判断，逻辑操作，所以，看了半天代码，也没有发现这个变量是用来做什么的，麻烦解释一下，谢谢。

**Comment by mzule** [comment]
@erhutime opened 表示侧边栏有没有完全打开的一个状态，percent == 1 代表完全打开， percent == 0 代表完全隐藏，只有完全打开的时候，菜单才有 hover 状态。

**Comment by erhutime** [comment]
个人感觉，不需要这个参数吧？DrawerLayout里面记得有方法可以判断出打开，或者关闭的状态；个人建议，使用一个float percent来进行判断，是不是有点奇怪？

**Comment by mzule** [comment]
@erhutime 也可以！就是要在 setTouchY 方法里面多加一个参数表示是否完全打开。使用 float 判断是会有些奇怪，不过对于 1、0 这种边界值，我觉得还是 ok 的。
