### ISSUE TITLE
How to use in CoordinatorLayout

### ISSUE THREAD

**Issue by tellfa** [mzule/FantasySlide#5]
How to use this library in CoordiantorLayout?

**Comment by L-Master** [comment]
1. **导入Library后报错.**
   `Error:Plugin with id 'com.github.dcendents.android-maven' not found.`
2. 重新写你的demo的时候碰到一个问题  CircleImageView 找不到,app:civ_border_color这个attrs找不到.所以编译通不过.
   `
               <com.github.mzule.fantasyslide.widget.CircleImageView
                   android:layout_width="110dp"
                   android:layout_height="110dp"
                   android:layout_margin="10dp"
                   android:src="@drawable/me"
                   app:civ_border_color="@color/menu_text_color"
                   app:civ_border_width="2dp" />
   `

> AndroidStudio 2.2  
> compileSdkVersion 25
>     buildToolsVersion "25.0.0"
>     defaultConfig {
>         applicationId "me.xiangbei.fantsydemo"
>         minSdkVersion 16
>         targetSdkVersion 25

**Comment by petrelprince** [comment]
我也遇到了同样的问题， 我是这样解决的 ，编译通过。
添加依赖
compile 'de.hdodenhof:circleimageview:2.1.0'
