### ISSUE TITLE
Error:(49, 1) A problem occurred evaluating project ':library'. > Could not read script 'https://raw.githubusercontent.com/nuuneoi/JCenter/master/installv1.gradle'.    > raw.githubusercontent.com

### ISSUE THREAD

**Issue by amit-upadhyay-IT** [mzule/FantasySlide#6]
I am importing this library manually in my project (not using the gradle dependency). I keep getting this error after some period of time. Actually whenever I get this error I clean my project and then the problem vanishes but again after some time it occurs. So I was searching for the permanent fix of this problem.

My library build.gradle file is:

apply plugin: 'com.android.library'

ext {
    bintrayRepo = 'maven'
    bintrayName = 'fantasy-slide'

    publishedGroupId = 'com.github.ms.fantasyslide'
    libraryName = 'FantasySlide'
    artifact = 'library'

    libraryDescription = 'FantasySlide'

    siteUrl = 'https://github.com/ms/FantasySlide/'
    gitUrl = 'https://github.com/ms/FantasySlide.git'

    libraryVersion = '1.0.4'

    developerId = 'ms'
    developerName = 'Cao Dongping'
    developerEmail = 'mzule4j@gmail.com'

    licenseName = 'The Apache Software License, Version 2.0'
    licenseUrl = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
    allLicenses = ["Apache-2.0"]
}

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.0"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile 'com.android.support:appcompat-v7:23.2.0'
}

apply from: 'https://raw.githubusercontent.com/nuuneoi/JCenter/master/installv1.gradle'
apply from: 'https://raw.githubusercontent.com/nuuneoi/JCenter/master/bintrayv1.gradle'

The error I get is:

Error:(49, 1) A problem occurred evaluating project ':library'.
> Could not read script 'https://raw.githubusercontent.com/nuuneoi/JCenter/master/installv1.gradle'.
   > raw.githubusercontent.com

**Comment by mzule** [comment]
You can just remove these code below. 

```
apply from: 'https://raw.githubusercontent.com/nuuneoi/JCenter/master/installv1.gradle'
apply from: 'https://raw.githubusercontent.com/nuuneoi/JCenter/master/bintrayv1.gradle'
```

They are used to publish library to jcenter for public usage.
