### ISSUE TITLE
Can't easily tell which index was touched in SimpleFantasyListener.onHover(View view)

### ISSUE THREAD

**Issue by ghost** [mzule/FantasySlide#8]
Could you add an index to the method please? I would very much appreciate it :)

For now I'm just using view tags to manipulate the views by index

**Comment by mzule** [comment]
Yes! It is a good suggestion. I will do it next week!

**Comment by mzule** [comment]
@burntapples Done with new version 1.0.5

**Comment by ghost** [comment]
Thank you!
